# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFbPhotos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFbPhotos
  
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  
  target 'MyFbPhotosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyFbPhotosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
